name: scrap and save Wikipedia OTD to PGSQL

on:
  schedule:
   - cron: '30 0 * * *'  # once a day at 01 AM UTC (07:30 WIB).

jobs:
  scrap-n-save:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v3
       with:
         python-version: '3.10' 
     - run: |
        python -m pip install --upgrade pip
        pip install pandas bs4 psycopg2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - run: python3 scrap_n_save_otd.py
