name: tweet TFP

on:
  schedule:
    #- cron: '0 */2 * * *'  # every 5 minutes for testing.
    - cron: '15 3 * *'  # once a day at 01 AM UTC (10:15 WIB).

jobs:
  publish-data:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v3
       with:
         python-version: '3.10' 
     - run: |
        python -m pip install --upgrade pip
        pip install pandas bs4 psycopg2 tweepy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - run: python3 tweet_tfp.py
